/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fact.h"

int *
fact_1_svc(val *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	
	int i,n,fact=1;
	n=argp->a;
	for(i=1;i<=n;i++){
		fact=fact*i;
	}
	 result=fact;
	return &result;
}
